FROM jupyter/minimal-notebook

LABEL MAINTAINER=prov@knmi

USER root

RUN apt-get update -qq && apt-get install -qqy \
	git \
    apt-transport-https \
    ca-certificates \
    curl \
    lxc \
    iptables \
    python-setuptools
    
RUN pip install cwlref-runner

USER $NB_USER

RUN mkdir -p /home/$NB_USER/

WORKDIR /home/$NB_USER/

RUN mkdir -p /home/$NB_USER/epos-cwl-workflows/

RUN git clone https://github.com/andrejsim/epos-cwl-workflows.git

RUN mkdir -p /home/$NB_USER/science-service/

RUN git clone https://github.com/andrejsim/science-service.git

USER root

# dispel4py integration
RUN apt-get update -qq && apt-get install -qqy \
	wget \
	curl \
	python-dev \
	python-pip \
	python-setuptools \
	git \
	openmpi-bin \
	openmpi-common \
	libopenmpi-dev \
	-y

RUN pip install mpi4py

# install dispel4py latest
RUN pip install git+git://github.com/aspinuso/dispel4py.git@master

COPY run_workflow.sh /usr/local/bin/

USER $NB_USER

