FROM jupyter/minimal-notebook


LABEL 	MAINTAINER=prov@knmi \
		USER=mihajlov

USER root

RUN apt-get update -qq && apt-get install -qqy \
	git \
    apt-transport-https \
    ca-certificates \
    curl \
    lxc \
    iptables \
    python-setuptools
    
RUN pip install cwlref-runner

RUN mkdir -p /home/test/

WORKDIR /home/test

RUN mkdir -p /home/test/epos-cwl-workflows/

RUN git clone https://github.com/andrejsim/epos-cwl-workflows.git

WORKDIR /home/test/epos-cwl-workflows


CMD bash